# Generated by Django 5.2.14 on 2026-06-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_carlead_vehicle_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlead',
            name='is_registered',
            field=models.CharField(blank=True, choices=[('yes', 'Ja'), ('no', 'Nein')], default='', max_length=3),
        ),
    ]
