# Generated by Django 5.2.14 on 2026-06-01 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_carlead_is_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('purchase_contract', 'Kaufvertrag'), ('invoice_email', 'Rechnung & E-Mail')], max_length=32, unique=True)),
                ('file', models.FileField(upload_to='dealer_templates/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dealer_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumentenvorlage',
                'verbose_name_plural': 'Dokumentenvorlagen',
                'ordering': ['template_type'],
            },
        ),
    ]
